/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2019-07-07 08:27:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class canvas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("  <script type=\"application/javascript\">\r\n");
      out.write("    function draw() {\r\n");
      out.write("    \tvar vec=[1,0,1,0,1,0,0,1,1,1,1,1,0,0,0,0,0];\r\n");
      out.write("      var canvas = document.getElementById(\"canvas\");\r\n");
      out.write("      if (canvas.getContext) {\r\n");
      out.write("        var ctx = canvas.getContext(\"2d\");\r\n");
      out.write("\t\tvar j=0;\r\n");
      out.write("    for(i=0; i<3; i++){\r\n");
      out.write("    \tj+=30;\r\n");
      out.write("    \tctx.beginPath();\r\n");
      out.write("        var centerX = (canvas.width / 2)+j;\r\n");
      out.write("        var centerY = (canvas.height / 2)+j;\r\n");
      out.write("        var radius = 15;        \r\n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\r\n");
      out.write("        if(vec[i] == 1){\r\n");
      out.write("       \t\tctx.fillStyle = 'green';\r\n");
      out.write("        }else{\r\n");
      out.write("        \tctx.fillStyle = 'red';\r\n");
      out.write("        }\r\n");
      out.write("        ctx.fill();\r\n");
      out.write("        ctx.lineWidth = 1;\r\n");
      out.write("    }\r\n");
      out.write("    j=0;\r\n");
      out.write("    for(i=3;i<6;i++){\r\n");
      out.write("    \tj+=40;\r\n");
      out.write("    \tctx.beginPath();\r\n");
      out.write("        var centerX = (canvas.width / 2)+125;\r\n");
      out.write("        var centerY = (canvas.height / 2)-40+j;\r\n");
      out.write("        var radius = 15;        \r\n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\r\n");
      out.write("        if(vec[i] == 1){\r\n");
      out.write("       \t\tctx.fillStyle = 'green';\r\n");
      out.write("        }else{\r\n");
      out.write("        \tctx.fillStyle = 'red';\r\n");
      out.write("        }\r\n");
      out.write("        ctx.fill();\r\n");
      out.write("        ctx.lineWidth = 1;    \r\n");
      out.write("    }\r\n");
      out.write("    j=0;\r\n");
      out.write("    for(i=6;i<8;i++){\r\n");
      out.write("    \tj+=30;\r\n");
      out.write("    \tctx.beginPath();\r\n");
      out.write("        var centerX = (canvas.width / 2)+30 +j;\r\n");
      out.write("        var centerY = (canvas.height / 2)-15 +j;\r\n");
      out.write("        var radius = 15;        \r\n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\r\n");
      out.write("        if(vec[i] == 1){\r\n");
      out.write("       \t\tctx.fillStyle = 'green';\r\n");
      out.write("        }else{\r\n");
      out.write("        \tctx.fillStyle = 'red';\r\n");
      out.write("        }\r\n");
      out.write("        ctx.fill();\r\n");
      out.write("        ctx.lineWidth = 1;    \r\n");
      out.write("    }\r\n");
      out.write("    j=0;\r\n");
      out.write("    for(i=8;i<9;i++){\r\n");
      out.write("    \tj+=30;\r\n");
      out.write("    \tctx.beginPath();\r\n");
      out.write("        var centerX = (canvas.width / 2)+92;\r\n");
      out.write("        var centerY = (canvas.height / 2)+5;\r\n");
      out.write("        var radius = 15;        \r\n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\r\n");
      out.write("        if(vec[i] == 1){\r\n");
      out.write("       \t\tctx.fillStyle = 'green';\r\n");
      out.write("        }else{\r\n");
      out.write("        \tctx.fillStyle = 'red';\r\n");
      out.write("        }\r\n");
      out.write("        ctx.fill();\r\n");
      out.write("        ctx.lineWidth = 1;    \r\n");
      out.write("    } \r\n");
      out.write("      }\r\n");
      out.write("      }\r\n");
      out.write("  </script>\r\n");
      out.write(" </head>\r\n");
      out.write(" <body onload=\"draw();\">\r\n");
      out.write("   <canvas id=\"canvas\" width=\"1024\" height=\"1024\"></canvas>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
