/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2019-07-07 21:04:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testCanvas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<title>Usher</title>\n");
      out.write("<meta name=\"ROBOTS\" content=\"NOINDEX, NOFOLLOW\">\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"css/animate.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"css/admin.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"plugins/data-tables/DT_bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("<!-- <link rel=\"shortcut icon\" href=\"images/BauerMecanicaLogo2.png\" />\n");
      out.write(" -->\n");
      out.write("<script src=\"js/jquery-1.12.js\"></script>\n");
      out.write(" \n");
      out.write(" <script src=\"js/jPushMenu.js\"></script> \n");
      out.write("<script src=\"js/side-chats.js\"></script>\n");
      out.write("\n");
      out.write("  <script type=\"application/javascript\">\n");
      out.write("    function draw() {\n");
      out.write("    \tvar vec=[1,0,1,0,1,0,0,1,1,1,1,1,0,0,0,0,0,1];\n");
      out.write("      var canvas = document.getElementById(\"canvas\");\n");
      out.write("      if (canvas.getContext) {\n");
      out.write("        var ctx = canvas.getContext(\"2d\");\n");
      out.write("\t\t\n");
      out.write("    //los tres de la izquierda en diagonal    \n");
      out.write("        var j=0;\n");
      out.write("    for(i=0; i<3; i++){\n");
      out.write("    \tj+=30;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+j;\n");
      out.write("        var centerY = (canvas.height / 2)+j;\n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    //los 3 del medio en vertical\n");
      out.write("    j=0;\n");
      out.write("    for(i=3;i<6;i++){\n");
      out.write("    \tj+=40;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+125;\n");
      out.write("        var centerY = (canvas.height / 2)-40+j;\n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    // los 2 siguientes de la izquierda en el medio\n");
      out.write("    j=0;\n");
      out.write("    for(i=6;i<8;i++){\n");
      out.write("    \tj+=30;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+30 +j;\n");
      out.write("        var centerY = (canvas.height / 2)-15 +j;\n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    //el de arriba a la izquierda de los 3 del medio verticales \n");
      out.write("    j=0;\n");
      out.write("    for(i=8;i<9;i++){\n");
      out.write("    \tj+=30;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+92;\n");
      out.write("        var centerY = (canvas.height / 2)+5;\n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    } \n");
      out.write("    \n");
      out.write("    j=0;\n");
      out.write("    for(i=9;i<12;i++){\n");
      out.write("    \tj+=40;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+180;\n");
      out.write("        var centerY = (canvas.height / 2)-40+j; \n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    } \n");
      out.write("    \n");
      out.write("    // segunda columna del medio a la derecha\n");
      out.write("    j=0;\n");
      out.write("    for(i=12;i<15;i++){\n");
      out.write("    \tj+=40;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+215; \n");
      out.write("        var centerY = (canvas.height / 2)+j-32;  \n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    // 2 ante ultimos de la derecha\n");
      out.write("    \n");
      out.write("    j=0;\n");
      out.write("    for(i=15;i<17;i++){\n");
      out.write("    \tj+=40;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+250; \n");
      out.write("        var centerY = (canvas.height / 2)+j-20 ;  \n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    //ultimo de la derecha arriba\n");
      out.write("    j=0;\n");
      out.write("    for(i=17;i<18;i++){\n");
      out.write("    \tj+=40;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)+280; \n");
      out.write("        var centerY = (canvas.height / 2)+j;  \n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("/*     j=0;\n");
      out.write("    for(i=12;i<15;i++){\n");
      out.write("    \tj+=30;\n");
      out.write("    \tctx.beginPath();\n");
      out.write("        var centerX = (canvas.width / 2)-j; \n");
      out.write("        var centerY = (canvas.height / 2)-j;  \n");
      out.write("        var radius = 15;        \n");
      out.write("        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);\n");
      out.write("        if(vec[i] == 1){\n");
      out.write("       \t\tctx.fillStyle = 'green';\n");
      out.write("        }else{\n");
      out.write("        \tctx.fillStyle = 'red';\n");
      out.write("        }\n");
      out.write("        ctx.fill();\n");
      out.write("        ctx.lineWidth = 1;    \n");
      out.write("    } */\n");
      out.write("    \n");
      out.write("      }\n");
      out.write("      }\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body onload=\"draw();\" class=\"light_theme left_nav_fixed atm-spmenu-push\" style=\"\">\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("  <!--\\\\\\\\\\\\\\ wrapper Start \\\\\\\\\\\\-->\n");
      out.write("  <div class=\"header_bar\">\n");
      out.write("  \n");
      out.write("    <!--\\\\\\\\\\\\\\ header Start \\\\\\\\\\\\-->\n");
      out.write("    <div class=\"brand\">\n");
      out.write("      <!--\\\\\\\\\\\\\\ brand Start \\\\\\\\\\\\-->\n");
      out.write("      <div class=\"logo\" style=\"display:block\">admin <span class=\"theme_color\">USHER</span></div></div>\n");
      out.write("    \n");
      out.write("    </div>\n");
      out.write("    <!--\\\\\\\\\\\\\\ brand end \\\\\\\\\\\\-->\n");
      out.write("        <div class=\"header_top_bar\"> \n");
      out.write("     <div class=\"header_top_bar\" style=\"background-image: url(images/BauerBannerDefinitivo.png)\">\n");
      out.write("      <!--\\\\\\\\\\\\\\ header top bar start \\\\\\\\\\\\-->\n");
      out.write("    <a href=\"javascript:void(0);\" class=\"menutoggle\"> <i class=\"fa fa-bars\"></i></a>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("    <!--\\\\\\\\\\\\\\ header top bar end \\\\\\\\\\\\-->\n");
      out.write("  </div>\n");
      out.write("  <!--\\\\\\\\\\\\\\ header end \\\\\\\\\\\\-->\n");
      out.write(" </div> \n");
      out.write("  <div class=\"inner\" style=\"width:100%\">\n");
      out.write("    <!--\\\\\\\\\\\\\\ inner start \\\\\\\\\\\\-->\n");
      out.write("    <div class=\"left_nav\">\n");
      out.write("      <!--\\\\\\\\\\\\\\left_nav start \\\\\\\\\\\\-->\n");
      out.write("      <div class=\"search_bar\"> <i class=\"fa fa-home\"></i>\n");
      out.write("        <a type=\"text\" class=\"search\" href=\"index.jsp\">INICIO</a>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"slimScrollDiv\" style=\"position: relative; width: auto; height: 70px;\"><div class=\"left_nav_slidebar\" >\n");
      out.write("        <ul>\n");
      out.write("<li><a href=\"user2\">USUARIOS</a></li>\n");
      out.write("<li><a href=\"canvas\">QUORUM</a></li>\n");
      out.write("      </ul>\n");
      out.write("      </div><div class=\"slimScrollBar\" style=\"background: rgb(161, 178, 189); width: 5px; position: absolute; top: 0px; border-radius: 7px; z-index: 99; right: 1px; height: 30px; display: none; opacity: 0.4;\"></div><div class=\"slimScrollRail\" style=\"width: 5px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;\"></div></div>\n");
      out.write("    </div>\n");
      out.write("    <!--\\\\\\\\\\\\\\left_nav end \\\\\\\\\\\\-->\n");
      out.write("    <div class=\"contentpanel\" style=\"min-height:600px;position:relative;width:100%\" >\n");
      out.write("   <!--  <div class=\"contentpanel\" style=\"background-image: url('images/MECANICABAUER.jpg');min-height: 600px;\"> -->\n");
      out.write("         <!--\\\\\\\\\\\\\\ contentpanel start\\\\\\\\\\\\-->\n");
      out.write("      \n");
      out.write("      <div class=\"pull-left breadcrumb_admin clear_both\">\n");
      out.write("        <div class=\"pull-left page_title theme_color\">\n");
      out.write("          <h1>PANEL DE QUORUM</h1>\n");
      out.write("          </div>\n");
      out.write("        <div class=\"pull-right\">\n");
      out.write("          <ol class=\"breadcrumb\">\n");
      out.write("            <li><a href=\"#\">Principal</a></li>\n");
      out.write("            <li><a href=\"#\">QUORUM</a></li>\n");
      out.write("            \n");
      out.write("          </ol>\n");
      out.write("        </div>\n");
      out.write("      </div> \n");
      out.write("      <canvas id=\"canvas\" width=620px height=230px ></canvas>  \n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
